# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# message "Welcome, Danger." if github.pr_author == "aldomddev"

# gem "rails"
